"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    signSuffix: '.lzy.zip',
    splitSize: '50m',
    maxSize: '99.5m',
    supportExt: [
        'doc',
        'docx',
        'zip',
        'rar',
        'apk',
        'ipa',
        'txt',
        'exe',
        '7z',
        'e',
        'z',
        'ct',
        'ke',
        'cetrainer',
        'db',
        'tar',
        'pdf',
        'w3x',
        'epub',
        'mobi',
        'azw',
        'azw3',
        'osk',
        'osz',
        'xpa',
        'cpk',
        'lua',
        'jar',
        'dmg',
        'ppt',
        'pptx',
        'xls',
        'xlsx',
        'mp3',
        'iso',
        'img',
        'gho',
        'ttf',
        'ttc',
        'txf',
        'dwg',
        'bat',
        'imazingapp',
        'dll',
        'crx',
        'xapk',
        'conf',
        'deb',
        'rp',
        'rpm',
        'rplib',
        'mobileconfig',
        'appimage',
        'lolgezi',
        'flac',
        'cad',
        'hwt',
        'accdb',
        'ce',
        'xmind',
        'enc',
        'bds',
        'bdi',
        'ssf',
        'it',
    ],
};
